// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcX-XqbSR_NqvuRQnBUnLFa8mlVghNtxk',
    appId: '1:484366291251:web:9faec9e61c21bd062a6e46',
    messagingSenderId: '484366291251',
    projectId: 'book-for',
    authDomain: 'book-for.firebaseapp.com',
    databaseURL: 'https://book-for-default-rtdb.firebaseio.com',
    storageBucket: 'book-for.appspot.com',
    measurementId: 'G-JJDMEXZGPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFh56eTAFF6muwmFFWDh0_tPkf3ixA35w',
    appId: '1:484366291251:android:abddf5166748fd8d2a6e46',
    messagingSenderId: '484366291251',
    projectId: 'book-for',
    databaseURL: 'https://book-for-default-rtdb.firebaseio.com',
    storageBucket: 'book-for.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe1SoasO35ctr59o2CAgCbq8XNTywCppc',
    appId: '1:484366291251:ios:cf2bd7ce99134e582a6e46',
    messagingSenderId: '484366291251',
    projectId: 'book-for',
    databaseURL: 'https://book-for-default-rtdb.firebaseio.com',
    storageBucket: 'book-for.appspot.com',
    iosClientId: '484366291251-p2o5kbmt9c06g8pj734r4c59tf43i212.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe1SoasO35ctr59o2CAgCbq8XNTywCppc',
    appId: '1:484366291251:ios:cf2bd7ce99134e582a6e46',
    messagingSenderId: '484366291251',
    projectId: 'book-for',
    databaseURL: 'https://book-for-default-rtdb.firebaseio.com',
    storageBucket: 'book-for.appspot.com',
    iosClientId: '484366291251-p2o5kbmt9c06g8pj734r4c59tf43i212.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
